const syspath = require('path')
const { expect } = require('code')
const { run } = require('./helpers')

describe('integration: manifest', () => {
  const cwd = `${__dirname}/mock`

  it('generates correct manifest object', async () => {
    const { stdout } = await run('manifest', { cwd })
    const res = JSON.parse(stdout)
    expect(res.path).to.equal('')
    expect(res.draft).to.be.false()
    expect(res.title).to.equal('Mock')
    expect(res.url).to.equal('/')
    expect(res.input).to.equal(syspath.resolve(__dirname, 'mock/readme.md'))
    expect(res.outputDir).to.equal('.gitdocs_build/')
    expect(res.items[0].path).to.equal('foo')
    expect(res.items[0].draft).to.be.false()
    expect(res.items[0].title).to.equal('The Foo')
    expect(res.items[0].url).to.equal('/foo/')
    expect(res.items[0].input).to.equal(syspath.resolve(__dirname, 'mock/foo/index.md'))
    expect(res.items[0].outputDir).to.equal('.gitdocs_build/foo/')
    expect(res.items[0].items).to.have.length(3)
    expect(res.items[4].path).to.equal('external.md')
    expect(res.items[4].title).to.equal('GitDocs')
    expect(res.items[4].url).to.equal('/gitdocs/')
    expect(res.items[4].input).to.match(/\/@repos\/gitdocs/)
    expect(res.items[4].outputDir).to.equal('.gitdocs_build/gitdocs/')
    expect(res.items[4].items).to.have.length(1)
    expect(res.items[4].items[0].path).to.equal('externals.md')
    expect(res.items[4].items[0].title).to.equal('Externals')
    expect(res.items[4].items[0].url).to.equal('/gitdocs/externals/')
  })
})
