const { expect } = require('chai')
const path = require('./path')

describe('unit: utils/path', () => {
  it('routify()', async () => {
    expect(path.routify('foo/bar')).to.equal('/foo/bar/')
    expect(path.routify('/foo/bar')).to.equal('/foo/bar/')
    expect(path.routify('/foo/bar/index')).to.equal('/foo/bar/')
    expect(path.routify('/foo/bar/index.md')).to.equal('/foo/bar/')
    expect(path.routify('/foo/bar/index.html')).to.equal('/foo/bar/')
    expect(path.routify('/foo/bar/baz.md')).to.equal('/foo/bar/baz/')
    expect(path.routify('/foo/bar/')).to.equal('/foo/bar/')
    expect(path.routify('foo')).to.equal('/foo/')
    expect(path.routify('/')).to.equal('/')
    expect(path.routify('')).to.equal('/')
  })

  it('outputify()', async () => {
    expect(path.outputify('/foo.md', { ext: 'html' })).to.equal('/foo/index.html')
    expect(path.outputify('/foo.md', { ext: 'js' })).to.equal('/foo/index.js')
    expect(path.outputify('/foo/index.md')).to.equal('/foo/')
    expect(path.outputify('/foo/bar.md', { ext: 'html' })).to.equal('/foo/bar/index.html')
    expect(path.outputify('/foo/bar/index.md', { ext: 'html' })).to.equal('/foo/bar/index.html')
    expect(path.outputify('/foo/bar/index.html', { ext: 'html' })).to.equal('/foo/bar/index.html')
    expect(path.outputify('/foo/bar', { ext: 'html' })).to.equal('/foo/bar/index.html')
    expect(path.outputify('/foo/bar/', { ext: 'html' })).to.equal('/foo/bar/index.html')
    expect(path.outputify('/foo/bar/', { replace: ['/foo', '/baz'] })).to.equal('/baz/bar/')
    expect(path.outputify('foo/bar')).to.equal('foo/bar/')
    expect(path.outputify('/', { ext: 'html' })).to.equal('/index.html')
    expect(path.outputify('/')).to.equal('/')
    expect(path.outputify('', { ext: 'html' })).to.equal('/index.html')
    expect(path.outputify('')).to.equal('/')
  })

  it('titlify()', async () => {
    expect(path.titlify('foo')).to.equal('Foo')
    expect(path.titlify('foo-bar')).to.equal('Foo Bar')
    expect(path.titlify('foo-bar.md')).to.equal('Foo Bar')
    expect(path.titlify('foo/bar/baz-qux.md')).to.equal('Baz Qux')
    expect(path.titlify('/foo-bar/')).to.equal('Foo Bar')
    expect(path.titlify('/foo-bar/index')).to.equal('Foo Bar')
    expect(path.titlify('/foo-bar/index.md')).to.equal('Foo Bar')
    expect(path.titlify('/foo-bar/baz-qux')).to.equal('Baz Qux')
    expect(path.titlify('/foo-bar/baz-qux/')).to.equal('Baz Qux')
  })

  it('slugify()')
})
